Deprecate Kubeflow Addon
canonical/microk8s pull request #2923
Opened 2022-02-15 14:22 UTC by DomFleischmann

The Charmed Kubeflow team has decided to deprecate the Microk8s Kubeflow
Addon. This is due to the upstream community struggling to keep up to
date with the latest Kubernetes versions. Additionally the Charmed
Kubeflow team wants to standardize on one unique installation experience
instead of having to support multiple ones.

Kubeflow will still be available on Microk8s by following these new
installation instructions:
https://charmed-kubeflow.io/docs/quickstart

2022-02-16 15:46 UTC, grobbie requested changes

2022-02-16 15:46 UTC, grobbie commented on microk8s-resources/actions/enable.kubeflow.sh
> +    print("This addon is no longer supported, instead please follow the quick start guide to install Charmed Kubeflow on Microk8s: ")
```suggestion
    print("This addon is no longer supported, instead please follow the quick start guide to install Charmed Kubeflow on MicroK8s: ")
```

2022-03-09 14:15 UTC, ktsakalozos commented
Hi @DomFleischmann, do you plan to address the failing Kubeflow tests?

2022-03-09 14:23 UTC, DomFleischmann commented
> Hi @DomFleischmann, do you plan to address the failing Kubeflow tests?

I think we might as well disable them, what do you think? Should I just remove them?

2022-03-09 21:11 UTC, ktsakalozos commented
> Should I just remove them?

Yes, that would be best.

2022-03-14 06:33 UTC, ktsakalozos commented
Thank you for this PR @DomFleischmann

2022-03-14 06:33 UTC, merged