Do not load the community repo
canonical/microk8s pull request #2982
Opened 2022-03-14 10:51 UTC by ktsakalozos

With this PR we stop loading the community repository by default. This was we do not clutter the UX with often irrelevant addons. If however we detect that an addon is in the community repository we prompt the user to enable the repository with a `microk8s enable community` call.

2022-03-14 11:15 UTC, neoaggelos requested changes

2022-03-14 11:15 UTC, neoaggelos commented on scripts/wrappers/common/utils.py
> +                click.echo("    mcirok8s enable community")
I presume this is a typo

2022-03-14 11:15 UTC, neoaggelos commented on snap/snapcraft.yaml
> +      echo "core" > addons/.auto-add
I'd rather this was changed in [set-env-variables.sh] instead (https://github.com/ubuntu/microk8s/blob/9536527e31d0d4d9c59f529d247c152625e68af5/build-scripts/set-env-variables.sh#L56)

2022-03-15 07:23 UTC, neoaggelos approved these changes

2022-03-15 10:39 UTC, balchua approved these changes

2022-03-15 13:46 UTC, merged