Make sure to use microk8s.kubectl
canonical/microk8s pull request #3176
Opened 2022-05-31 01:05 UTC by nobuto-m

If we call kubectl simply, the system installed kubectl has precedence.
That may lead to some weird issues like an error due to a discrepancy
between kubectl cli and kubernetes API versions.

Closes: #3175

#### Summary

#### Changes

#### Testing

#### Possible Regressions

#### Checklist

* [x] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [ ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [ ] The introduced changes are covered by unit and/or integration tests.

#### Notes

2022-06-01 05:46 UTC, nobuto-m commented
I exercised a manual testing as per the description, and confirmed working as expected for the record.

> #### Testing
> 
>     1. prepare `kubectl` on the system that always fails
>        ```
>        $ sudo ln -s /bin/false /usr/local/bin/kubectl
>        $ kubectl; echo $?
>        1
>        ```
> 
>     2. install the patched snap
>        ```
>        $ sudo snap install --dangerous --classic ./microk8s.snap
>        ```
> 
>     3. execute addon enable command, which was failing in [microk8s.kubectl should be used for internal health checking as using the system kubectl may fail #3175](https://github.com/canonical/microk8s/issues/3175)
> 
>     4. confirm the command now works.

2022-06-01 05:46 UTC, nobuto-m commented
I exercised a manual testing as per the description, and confirmed working as expected for the record.

> #### Testing
> 
>     1. prepare `kubectl` on the system that always fails
>        ```
>        $ sudo ln -s /bin/false /usr/local/bin/kubectl
>        $ kubectl; echo $?
>        1
>        ```
> 
>     2. install the patched snap
>        ```
>        $ sudo snap install --dangerous --classic ./microk8s.snap
>        ```
> 
>     3. execute addon enable command, which was failing in [microk8s.kubectl should be used for internal health checking as using the system kubectl may fail #3175](https://github.com/canonical/microk8s/issues/3175)
> 
>     4. confirm the command now works.

2022-06-03 13:08 UTC, neoaggelos requested changes
Thank you for this PR @nobuto-m

This is problematic for a few reasons, namely:
1. the /snap/bin folder may not be available in PATH, so `microk8s.kubectl` will not be available.
2. `microk8s.kubectl` will have issues in strict confinement, so we actively avoid using it inside the snap
3. the extra `kubeconfig` parameter is unnecessary if using microk8s.kubectl.

Note that these are not issues with the PR, they all pre-exist in the current state of the code as well.

Further, this code looks quite old, there is since a much better way of calling kubectl. See https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/reset.py#L23 and   https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/reset.py#L163 for details.

In general, it should suffie to change "kubectl" to `$SNAP.microk8s-kubectl.wrapper`, and remove the extra `kubeconfig` file location (it's already set in the wrapper script)

2022-06-03 13:36 UTC, nobuto-m commented
Thank you for the feedback.

> This is problematic for a few reasons, namely:
> 
>     1. the /snap/bin folder may not be available in PATH, so `microk8s.kubectl` will not be available.

Are you sure on this? I've tested this as per the test case, and `microk8s.kubectl` was actually called successfully.
https://github.com/canonical/microk8s/blob/3223749b74dead7c230406328a5a0daa20b13488/scripts/wrappers/common/utils.py#L43

>     2. `microk8s.kubectl` will have issues in strict confinement, so we actively avoid using it inside the snap

If that's the case, the original code was even worse since it's calling the **system**'s kubectl instead of kubectl inside the snap.

>     3. the extra `kubeconfig` parameter is unnecessary if using microk8s.kubectl.

Agreed.

> Note that these are not issues with the PR, they all pre-exist in the current state of the code as well.
> 
> Further, this code looks quite old, there is since a much better way of calling kubectl. See https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/reset.py#L23 and https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/reset.py#L163 for details.

If the current code and/or the legacy way is problematic, would you like to refactor those before or after this PR? Or do you expect me to do such refactoring?

> In general, it should suffie to change "kubectl" to `$SNAP.microk8s-kubectl.wrapper`, and remove the extra `kubeconfig` file location (it's already set in the wrapper script)

2022-06-03 13:48 UTC, nobuto-m commented
I've pushed another commit to use microk8s-kubectl.wrapper and will do a manual test later.

2022-06-04 06:59 UTC, nobuto-m commented
I believe the failure as:
FAILED tests/test-upgrade.py::TestUpgrade::test_upgrade
is not related to my chance since it looks like the recent commits have the same problem. In the meantime, I've manually tested the built snap and it works for a fresh installation as per the test case.

![Screenshot from 2022-06-04 15-57-41](https://user-images.githubusercontent.com/4356209/171988486-56c097e1-3f50-4fbf-83a6-b64eaee9e247.png)

2022-06-06 06:46 UTC, neoaggelos commented
> is not related to my chance since it looks like the recent commits have the same problem

Correct, this is unrelated to your changes.

2022-06-06 06:47 UTC, neoaggelos approved these changes
LGTM, thanks @nobuto-m

2022-06-06 06:54 UTC, nobuto-m commented
Thanks. In the meantime, would it be possible to backport this change down to 1.21 channel? 1.21 is required to deploy Kubeflow and the issue is obvious when microk8s is 1.21 and the system kubectl is newer like 1.24 when `kubectl get all` is called.

2022-06-06 07:15 UTC, neoaggelos commented
Yes, this needs to be backported to all supported stable tracks.

Note that with the release of 1.24, 1.21 is officially out of support, but I guess we can make an exception for this particular bugfix, given that KubeFlow is still stuck in 1.21

2022-06-06 07:31 UTC, merged