Fixed reconciliation of offloading patch for calico
canonical/microk8s pull request #3705
Opened 2023-01-27 11:54 UTC by berkayoz

#### Summary

Moved reconciliation of offloading patch from the reload process
#### Changes

Moved reconciliation of offloading patch from the reload process and added a flag so it's run on every install/upgrade
#### Testing

Manually tested.

#### Possible Regressions

#### Checklist

* [x] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [x] The introduced changes are covered by unit and/or integration tests.

#### Notes

2023-01-27 12:28 UTC, neoaggelos commented on snap/hooks/configure
> +  touch "${SNAP_DATA}/var/lock/try-offloading-patch"
patch offloading is a one-time configuration, so i'd suggest moving this to `install` instead.

2023-01-27 12:28 UTC, neoaggelos commented on microk8s-resources/default-hooks/reconcile.d/10-cni-restart
> +    rm "${SNAP_DATA}/var/lock/try-offloading-patch"
i would suggest `sed s,try-offloading-patch,offloading-patch-applied`

2023-01-27 12:28 UTC, neoaggelos reviewed
two small patches, other than that we should be good to go!

2023-01-27 12:33 UTC, neoaggelos commented
Since we are on the subject, can you also add the following to the `env` section of `daemonset/calico-node` at `upgrade-scripts/000-switch-to-calico/resources/calico.yaml`?

```
- name: FELIX_FEATUREDETECTOVERRIDE
  value: ChecksumOffloadBroken=true
```

This would effectively prevent the issue from ever manifesting in all new clusters.

See the "manifest" section in https://projectcalico.docs.tigera.io/reference/felix/configuration

2023-01-27 13:45 UTC, neoaggelos commented on microk8s-resources/default-hooks/reconcile.d/10-cni-restart
> +    [ -e "${SNAP_DATA}/var/lock/try-offloading-patch" ] &&
How about this?
```suggestion
    ! [ -e "${SNAP_DATA}/var/lock/offloading-patch-applied" ] &&
```

Then you can also skip the `try-offloading-patch` entirely.

2023-01-30 08:25 UTC, neoaggelos requested changes
Almost there, one final fix and it should be good to merge!

2023-01-31 08:18 UTC, berkayoz commented on microk8s-resources/default-hooks/reconcile.d/10-cni-restart
> +    ! grep -q "ChecksumOffloadBroken" "${SNAP_DATA}/args/cni-network/cni.yaml" &&
Thanks for the reviews, added the required checks.

2023-01-31 08:26 UTC, neoaggelos approved these changes
LGTM, thanks @berkayoz!

2023-02-01 11:06 UTC, merged