Fixed error for worker node's leaving operation which caused unresponsiveness in the node
canonical/microk8s pull request #3793
Opened 2023-02-23 08:35 UTC by sachinkumarsingh092

#### Summary

The error occurred during the joining of the worker node. An empty serviceaccount was created which was not required by the microk8s agent and hence was causing the node to fail when it left the cluster.

Closes #3708 

#### Testing

Local testing.

#### Possible Regressions

#### Checklist

* [x] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [x] The introduced changes are covered by unit and/or integration tests.

#### Notes

Will also create backports for this.

2023-03-02 14:37 UTC, neoaggelos commented
Looks nice, what scenario are you testing these changes with?

2023-03-02 14:40 UTC, sachinkumarsingh092 commented
2 node. The control plane node has dns and rbac enabled.
Multiple join and leaves done by the worker node. The status is `running` on the worker node after this, which was not the case earlier.

2023-03-06 13:38 UTC, neoaggelos requested changes
`reset_cert_reissue()` is not relevant to the task at hand, and I don't think it is right to do this in worker nodes, since the ca.crt and ca.key are not valid.

I would suggest simply removing the `store_cert("serviceaccount.key", info["service_account_key"])` line instead.

2023-03-06 13:45 UTC, sachinkumarsingh092 commented
The error persists even after removing `store_cert("serviceaccount.key", info["service_account_key"])`. The error disappears only after adding `reset_cert_reissue()`.

2023-03-09 18:18 UTC, neoaggelos approved these changes
Looks good, one comment about the test

2023-03-09 18:18 UTC, neoaggelos commented on tests/test-cluster.py
> +                break
Is this enough time to prevent flaky failures?

2023-03-09 19:31 UTC, merged