the "--mem" long option is deprecated in favour of "--memory". Please…
canonical/microk8s pull request #4442
Opened 2024-02-27 21:11 UTC by themagiccog

the "--mem" long option is deprecated in favour of "--memory". Please… update any scripts, etc.

#### Summary
the "--mem" long option is deprecated in favour of "--memory". Please… update any scripts, etc.

#### Changes
change from --mem to --memory

#### Testing
N/A

#### Possible Regressions
No

#### Checklist

* [x] Read the [contributions](https://github.com/canonical/microk8s/blob/master/CONTRIBUTING.md) page.
* [x] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
* [x] The introduced changes are covered by unit and/or integration tests.

#### Notes
N/A

2024-02-28 13:19 UTC, neoaggelos reviewed
Hi @themagiccog! 

Thank you for the PR, there's more references to `--mem` in the code, would you mind making sure they are all updated?

Thank you!

2024-03-15 04:15 UTC, themagiccog reviewed
This looks good... Thanks

2024-03-15 04:16 UTC, themagiccog commented
You can proceed to merge.

2024-03-15 14:30 UTC, neoaggelos requested changes
There are still references and usage of `--mem` in the code, please address.

2025-04-11 07:22 UTC, petrutlucian94 commented
> the "--mem" long option is deprecated in favour of "--memory". Please… update any scripts, etc.

I don't see where the `--mem` setting of `microk8s install` was deprecated, we should avoid introducing breaking changes unless we have to.

2025-04-11 07:53 UTC, closed without merging